# Curated family metadata — one entry per source catalog (UL pending re-download)
FAMILIES = {
 'AERO 44 (2)': dict(id='aero-44', name='AERO 44 Aerospace Wires & Cables', segment='Aerospace & Defence',
   summary='Electron-beam cross-linked polyalkene insulated primary wires and cables for aircraft, avionics, military electronics, satellites and mass transit. 600V / 1000V / 2500V ratings; tin, silver or nickel coated copper conductors; single core, twisted and shielded constructions.',
   applications=['Aircraft hook-up & signal wiring','Avionics','Military electronics','Satellites & helicopters','Mass transit','Offshore platforms'],
   voltage='600V / 1000V / 2500V', temp='-65°C to +150°C (tin) / +200°C (Ag/Ni)',
   keywords=['aero 44','airframe wire','avionic cable','EBXL polyalkene','MIL aerospace wire','hookup wire']),
 'AERO 55 (1)': dict(id='aero-55', name='AERO 55 Aerospace Wires & Cables', segment='Aerospace & Defence',
   summary='Lightweight EBXL aerospace wires (AERO 55 family) for airframe and avionic wiring, including twisted, shielded, multicore and statistical-process-controlled airframe constructions, plus Sie-Foam twin-axial RF cables. 600V rated.',
   applications=['Airframe wiring','Avionics','Defence electronics','RF / data (twin-axial)'],
   voltage='600V', temp='-65°C to +200°C (typ.)',
   keywords=['aero 55','airframe wire','SPC airframe','twin axial','aerospace cable']),
 'Antenna Cable': dict(id='antenna', name='Antenna & Coaxial Cables', segment='Automotive & EV',
   summary='Coaxial antenna and RF data cables for automotive and general applications: RG 174/U, RG 58LL, FL9Y/FL09Y series, RTK-031 and twin RF constructions with attenuation data up to GHz range.',
   applications=['Automotive antenna & infotainment','GPS / GSM / radio','RF signal transmission','Telematics'],
   voltage='Signal / RF', temp='-40°C to +105°C (typ.)',
   keywords=['coaxial','antenna cable','RG 174','RG 58','FL9YBCY','FAKRA','RF cable','attenuation']),
 'Automotive cable Updated (1)': dict(id='automotive', name='Automotive Primary Cables', segment='Automotive & EV',
   summary='Full range of JIS / JASO / ISO automotive primary wires: AV, AVS, AVSS (PVC thin-wall), AVX/AEX (heat-resistant XLPE), CPE-FR, EB/HEB battery-vent, Auto 85–150 DIVUS/CIVUS classes and special screened constructions. RoHS compliant.',
   applications=['Starting, charging & lighting circuits','Signal & instrument wiring','Engine compartment wiring','Battery & vent lines','Trailers & trucks'],
   voltage='60V (low-voltage automotive)', temp='-40°C to +80/100/125°C by class',
   keywords=['AV','AVS','AVSS','AVX','AEX','FLRY','JIS C 3406','JASO D 611','ISO 6722','automotive wire','thin wall']),
 'Battery Cable': dict(id='battery', name='Battery Cables', segment='Automotive & EV',
   summary='Flexible battery cables for automotive and industrial starter/power connections with heavy copper conductors and abrasion-resistant insulation.',
   applications=['Vehicle starter & earth straps','Battery interconnects','DC power distribution'],
   voltage='60V DC (typ.)', temp='-40°C to +105°C (typ.)',
   keywords=['battery cable','starter cable','earth strap','booster cable']),
 'BS 5467 Power Cable updated': dict(id='bs5467-power', name='BS 5467 LV Power Cables', segment='Power & Industrial',
   summary='600/1000V XLPE-insulated, PVC/LSZH sheathed power cables to BS 5467, single and multicore, steel-wire armoured (SWA) and unarmoured, copper and aluminium conductors.',
   applications=['Fixed industrial power distribution','Building services','Switchgear tails','Underground / ducted circuits'],
   voltage='600/1000V', temp='90°C conductor (XLPE)',
   keywords=['BS 5467','SWA','armoured cable','XLPE power cable','LV power']),
 'Condiuts  catalogue 2020': dict(id='conduits', name='Polyamide Conduits & Fittings', segment='Railways & Rolling Stock',
   summary='Flexible polyamide corrugated conduits with PG/metric metal-thread end fittings, elbows, clamps, lock nuts, plugs, washers and sealing rings to RDSO/PE/SPEC/0138-2009 (Rev-1).',
   applications=['Rolling stock wiring protection','Locomotive harness routing','Industrial machine wiring'],
   voltage='—', temp='Class D (per RDSO spec)',
   keywords=['conduit','polyamide','corrugated','PG fitting','RDSO 0138','end fitting','cable protection']),
 'Diesel Locomotive updated': dict(id='emd-locomotive', name='Diesel Electric Locomotive (EMD) Cables', segment='Railways & Rolling Stock',
   summary='ATC 110°C/125°C cables to EMD / EDPS 179 & 304 specifications for diesel-electric locomotives, from single core power to multicore control constructions, up to 2100V.',
   applications=['Diesel-electric locomotive power & control','Traction equipment wiring','EMD OEM & retrofit'],
   voltage='600V – 2100V', temp='110°C / 125°C',
   keywords=['EMD','EDPS 179','EDPS 304','locomotive cable','diesel electric','ATC']),
 'EV Cable': dict(id='ev', name='EV & Charging Cables', segment='Automotive & EV',
   summary='High-voltage cables for electric vehicles and charging infrastructure: shielded and unshielded HV harness cables, charging (Mode 2/3) cables and thin-wall constructions with orange EV identification.',
   applications=['EV high-voltage harness','Charging guns & EVSE','Battery pack interconnects','Hybrid vehicles'],
   voltage='Up to 1000V AC / 1500V DC', temp='-40°C to +125/150°C by type',
   keywords=['EV cable','charging cable','high voltage harness','EVSE','orange cable','shielded HV']),
 'Fire resistence updated 18.04.26..': dict(id='fire-resistant', name='Fire Resistant Cables (FRX / H07Z)', segment='Fire Safety & Building',
   summary='EBXL FRX 100+/200+/400+ fire-resistant/fire-survival cables (armoured & unarmoured) and thermosetting H07Z-U/R/K, H05Z single-core 300/500V & 450/750V halogen-free wiring cables.',
   applications=['Fire alarm & emergency circuits','Public buildings & metros','Evacuation & safety systems','Panel wiring (H07Z)'],
   voltage='300/500V – 450/750V (wiring); LV (FRX)', temp='Up to 120°C operating; fire survival rated',
   keywords=['fire resistant','fire survival','FRX','H07Z','H05Z','LSZH','circuit integrity','IEC 60331']),
 'Flexible Cable updated': dict(id='sflex', name='SFLEX Flexible & Drag-Chain Cables', segment='Power & Industrial',
   summary='SFLEX CLASSIC 100–135 control cables (plain, CY braided-screen, SY steel-braid, H halogen-free variants), SFLEX SERVO 730 servo cables and SFLEX FD 810/820 drag-chain cables, 0.5–1kV.',
   applications=['Machine tools & automation','Drag chains / continuous flexing','Servo & VFD drives','Control panels'],
   voltage='0.5kV / 0.75kV / 1kV', temp='-5°C to +70/90°C (typ. fixed/flexing)',
   keywords=['flexible cable','control cable','CY','SY','drag chain','servo','FD cable','screened control']),
 'Fluoroelastomer': dict(id='fluoroelastomer', name='Fluoroelastomer 200°C Cables', segment='Railways & Rolling Stock',
   summary='EBXL fluoroelastomer-insulated flexible single-core cables for diesel locomotives, -55°C to +200°C continuous, with full type-test data (dielectric, insulation resistance, leakage).',
   applications=['Diesel locomotive engine areas','High-temperature power wiring','Traction auxiliaries'],
   voltage='Per locomotive spec (LV)', temp='-55°C to +200°C',
   keywords=['fluoroelastomer','200C cable','locomotive wire','high temperature']),
 'IS 1554 Control Cables': dict(id='is1554-control', name='IS 1554 PVC Control Cables', segment='Power & Industrial',
   summary='1100V PVC-insulated control cables up to 61 cores to IS 1554 Part 1: copper or aluminium, solid or stranded conductors, GI round-wire or flat-strip armoured and unarmoured.',
   applications=['Switchgear & MCC control wiring','Process industry instrumentation','Utility substations'],
   voltage='1100V', temp='70°C (PVC)',
   keywords=['IS 1554','control cable','armoured','multicore','PVC','61 core']),
 'IS 7098 Power Cable': dict(id='is7098-power', name='IS 7098 XLPE Power Cables', segment='Power & Industrial',
   summary='XLPE-insulated power cables to IS 7098: 1.1kV single & multicore, copper/aluminium, armoured and unarmoured, PVC outer sheath.',
   applications=['LT power distribution','Industrial feeders','Infrastructure & utilities'],
   voltage='1.1kV', temp='90°C conductor (XLPE)',
   keywords=['IS 7098','XLPE','power cable','LT cable','armoured','aluminium power']),
 'Power cable IS 7098': None,  # merged into is7098-power
 'Indian Railway Cables_10.04.26': dict(id='indian-railway', name='Indian Railway (RDSO) Cables', segment='Railways & Rolling Stock',
   summary='EBXL thin-wall flexible cables for Indian Railways electric locomotives and coaches: single core 750V–1.8/3kV HR 120°C, multicore control, sheathed and screened constructions per RDSO specifications.',
   applications=['Electric locomotives (WAP/WAG)','EMU / MEMU coaches','Traction control & auxiliaries'],
   voltage='Up to 1.8/3kV', temp='120°C (HR)',
   keywords=['indian railway','RDSO','locomotive cable','EBXL HR 120','traction cable','1.8/3 kV']),
 'Irrigation Communication Cable': dict(id='irrigation-comm', name='Irrigation & Communication Cables', segment='Communication & Instrumentation',
   summary='Cables for irrigation automation and outdoor communication: multicore signal/control cables with water-resistant, UV-stable constructions for decoder and sensor networks.',
   applications=['Irrigation decoder networks','Golf course / landscape control','Outdoor sensor & signal lines'],
   voltage='LV signal/control', temp='Outdoor rated, UV stable',
   keywords=['irrigation cable','decoder cable','communication cable','direct burial']),
 'Marine Cable (1)': dict(id='marine', name='Marine & Shipboard Cables', segment='Marine & Offshore',
   summary='ABS / IRS / Lloyd\'s approved shipboard cables: MGCH/MGH/MGSGO/MPRX control & power, FM/LM screened pairs, LKM/RFE/RFA halogen-free and fire-resistant series, SY braided wiring cables and EED 50-13 defence tables. XLPO insulated, EMC screened variants, 0.6/1kV.',
   applications=['Shipboard power & control','Naval / defence vessels (EED 50-13)','Offshore platforms','Instrumentation & comms on ships'],
   voltage='150/250V – 0.6/1kV', temp='90°C (XLPO), HF & FR variants',
   keywords=['marine cable','shipboard','ABS','Lloyds','IRS','EMC screened','halogen free','EED 50-13','offshore']),
 'Nuclear cables': dict(id='nuclear', name='Nuclear Grade Cables', segment='Nuclear & Energy',
   summary='EBXL-XLPE 90/120°C insulated, CSPE-sheathed 600V instrumentation, thermocouple-extension and UL Type TC power/control cables for nuclear facilities, with tinned copper conductors and drain-wire screened multi-pair constructions.',
   applications=['Nuclear power plant I&C','Safety-related circuits','Thermocouple extension','UL Type TC trays'],
   voltage='600V', temp='90°C / 120°C (EBXL-XLPE)',
   keywords=['nuclear cable','CSPE','UL Type TC','instrumentation','K1/K2/K3','EBXL XLPE']),
 'PW_125_Flexible_Single_Multicore_EBXL Cables': dict(id='pw-125', name='PW 125 Flexible EBXL Cables', segment='Power & Industrial',
   summary='PW 125 electron-beam cross-linked halogen-free flexible single & multicore cables for internal wiring of equipment, panels and appliances at high/low temperature extremes.',
   applications=['Panel & equipment internal wiring','Appliances','Luminaires & transformers'],
   voltage='LV (600/1000V class)', temp='125°C',
   keywords=['PW 125','EBXL','halogen free','internal wiring','panel wire']),
 'Rolling Stock cable updated': dict(id='rolling-stock', name='Rolling Stock Cables (BS EN 50306 / 50264)', segment='Railways & Rolling Stock',
   summary='Thin-wall and standard-wall EBXL rolling stock cables to BS EN 50306 (parts 2–4: single, multicore, screened, multipair) and BS EN 50264-3-1/-3-2, 300V AC to 1800/3000V AC, 90–105°C, halogen-free low smoke.',
   applications=['Metro & mainline rolling stock','Inter-coach & bogie wiring','Train control & multipair signal'],
   voltage='300V – 1800/3000V AC', temp='90°C / 105°C',
   keywords=['rolling stock','EN 50306','EN 50264','train cable','thin wall','multipair screened','LSZH']),
 'Rubber cable updated': dict(id='rubber', name='Rubber Flexible Cables', segment='Power & Industrial',
   summary='EPR-insulated, PCP/CSPE-sheathed rubber flexible cables: H07RN-F and equivalents for tools, sites, submersible pumps and mobile equipment.',
   applications=['Construction sites & tools','Submersible pumps','Mobile machinery & festoons','Temporary power'],
   voltage='450/750V (H07RN-F class)', temp='-25°C to +90°C',
   keywords=['H07RN-F','rubber cable','EPR','trailing cable','submersible','site cable']),
 'Sietherm 125 Flexible Single core': dict(id='sietherm-125', name='Sietherm 125 EBXL Wires', segment='Power & Industrial',
   summary='Sietherm 125 electron-beam cross-linked halogen-free flexible wires, single and multicore, for internal wiring at 125°C with low-temperature flexibility.',
   applications=['Panel internal wiring','Lighting & appliances','Transformer leads'],
   voltage='LV (600/1000V class)', temp='125°C',
   keywords=['sietherm 125','EBXL wire','halogen free','appliance wiring']),
 'Sietherm 125 Multicore': None,  # merged into sietherm-125
 'Sietherm 155 multicore': dict(id='sietherm-155', name='Sietherm 155 EBXL Wires', segment='Power & Industrial',
   summary='Sietherm 155 EBXL halogen-free wires, single and multicore, class 155°C for coil winding leads, motors and high-temperature equipment wiring; low smoke, low calorific value insulation.',
   applications=['Motor & coil leads','High-temp equipment wiring','Panel wiring'],
   voltage='LV (600/1000V class)', temp='155°C',
   keywords=['sietherm 155','class F wire','EBXL','motor lead wire']),
 'siethem 155 Single core': None,  # merged into sietherm-155
 'Silicone  Cable (1)': dict(id='silicone', name='Silicone Rubber Cables', segment='Power & Industrial',
   summary='Silicone rubber insulated cables from H05S-U/K 300/500V wiring types and SIHF/SIFL/SIAFF flexible cables to 1.8/3kV and 3.6/6kV Type F/FF/OF constructions (120–180°C), with glass-fibre braided variants.',
   applications=['Steel plants & foundries','Heaters & ovens','High-temp motor connections','Lighting'],
   voltage='300/500V – 3.6/6kV', temp='-60°C to +180°C',
   keywords=['silicone cable','H05S','SIHF','SIAFF','high temperature','glass braid','3.6/6 kV']),
 'Solar Booklets': dict(id='solar', name='Solar & PV Cables', segment='Renewable Energy',
   summary='EBXL XLPO 120°C solar DC cables (EN 50618 / IEC 62930 style), copper and aluminium, braided/screened variants, plus LV AC power cables (XLPE armoured/unarmoured) for solar plants.',
   applications=['PV string & array wiring','Solar farm DC mains','Inverter AC interconnects','Rooftop solar'],
   voltage='1.5kV DC (solar); 1.1kV AC (power)', temp='120°C (XLPO), 25-year UV design life',
   keywords=['solar cable','PV wire','EN 50618','H1Z2Z2-K','DC cable','XLPO','TUV']),
 'WELDING  New': dict(id='welding', name='Welding Cables', segment='Power & Industrial',
   summary='Flexible welding cables with fine-strand copper conductors and abrasion-resistant elastomer insulation, with duty-cycle current ratings and ambient derating tables.',
   applications=['Arc welding leads','Earth return leads','Workshop & site welding'],
   voltage='100V (welding class)', temp='Up to 85/90°C',
   keywords=['welding cable','welding lead','fine strand copper','duty cycle']),
 'Wind Energy': dict(id='wind', name='Wind Energy Cables', segment='Renewable Energy',
   summary='Torsion-resistant and flexible cables for wind turbines: H07ZZ-F, H07BN4-F, H07RN-F, NSGAFOU 3kV, SFLEX CY control, UL 21098 and EPR/EBXL/Silicone power cables (armoured & unarmoured) for loop, tower and array circuits.',
   applications=['Turbine loop / droop cables (torsion)','Tower power risers','Pitch & yaw control','Wind farm array circuits'],
   voltage='450/750V – 3kV (+ MV power)', temp='-40°C to +90/120°C',
   keywords=['wind turbine cable','torsion','H07ZZ-F','NSGAFOU','loop cable','wind farm']),
 'UL Cable v2': dict(id='ul-appliance', name='UL Appliance Wires & Cables', segment='Power & Industrial',
   summary='UL-style appliance wiring: UL 1015, 1028, 1032, 1275, 1283, 1284, 10269, 2127, 2128 and related styles — PVC and specialty insulated hook-up and internal wiring, single and multi-conductor, with UL wall thicknesses and conductor resistance data.',
   applications=['Appliance internal wiring','Control panels & switchboards','Electronic equipment hook-up','Export (UL-market) equipment'],
   voltage='300V – 1000V by UL style', temp='80°C – 105°C by style',
   keywords=['UL 1015','UL 1028','UL 1032','UL 10269','hook-up wire','appliance wire','AWM','UL style']),
}
MERGE_INTO={'Power cable IS 7098':'IS 7098 Power Cable','Sietherm 125 Multicore':'Sietherm 125 Flexible Single core','siethem 155 Single core':'Sietherm 155 multicore'}
PDF_FILE={  # datasheet download mapping (files in catalogue-pdfs/)
 'AERO 44 (2)':'AERO 44 (2).pdf','AERO 55 (1)':'AERO 55 (1).pdf','Antenna Cable':'Antenna Cable.pdf',
 'Automotive cable Updated (1)':'Automotive cable Updated (1).pdf','Battery Cable':'Battery Cable.pdf',
 'BS 5467 Power Cable updated':'BS 5467 Power Cable updated.pdf','Condiuts  catalogue 2020':'Condiuts  catalogue 2020.pdf',
 'Diesel Locomotive updated':'Diesel Locomotive updated.pdf','EV Cable':'EV Cable.pdf',
 'Fire resistence updated 18.04.26..':'Fire resistence updated 18.04.26...pdf','Flexible Cable updated':'Flexible Cable updated.pdf',
 'Fluoroelastomer':'Fluoroelastomer.pdf','IS 1554 Control Cables':'IS 1554 Control Cables.pdf',
 'IS 7098 Power Cable':'IS 7098 Power Cable.pdf','Power cable IS 7098':'Power cable IS 7098.pdf',
 'Indian Railway Cables_10.04.26':'Indian Railway Cables_10.04.26.pdf','Irrigation Communication Cable':'Irrigation Communication Cable.pdf',
 'Marine Cable (1)':'Marine Cable (1).pdf','Nuclear cables':'Nuclear cables.pdf',
 'PW_125_Flexible_Single_Multicore_EBXL Cables':'PW_125_Flexible_Single_Multicore_EBXL Cables.pdf',
 'Rolling Stock cable updated':'Rolling Stock cable updated.pdf','Rubber cable updated':'Rubber cable updated.pdf',
 'Sietherm 125 Flexible Single core':'Sietherm 125 Flexible Single core.pdf','Sietherm 125 Multicore':'Sietherm 125 Multicore.pdf',
 'Sietherm 155 multicore':'Sietherm 155 multicore.pdf','siethem 155 Single core':'siethem 155 Single core.pdf',
 'Silicone  Cable (1)':'Silicone  Cable (1).pdf','Solar Booklets':'Solar Booklets.pdf',
 'WELDING  New':'WELDING  New.pdf','Wind Energy':'Wind Energy.pdf','UL Cable v2':'UL Cable v2.pdf'}